final-project/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using final_project.Models;
using Microsoft.AspNetCore.Http;

namespace final_project.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult SignIn()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View();
            } else
            {
                return RedirectToAction("Welcome", "Admin", null);
            }
        }
    }
}

final-project/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using final_project.Models;
using final_project.Data;
using Microsoft.AspNetCore.Http;

namespace final_project.Controllers
{
    public class UserController : Controller
    {
        private readonly BookStoreContext _context;

        public UserController(BookStoreContext context)
        {
            _context = context;
        }

        [HttpPost]
        public IActionResult Login(string email, string password)
        {
            if (email == null || password == null)
            {
                TempData["LoginFailed"] = true;
                return Redirect("/Registration/SignIn");
            }

            var admin = _context.Admins.SingleOrDefault(u => u.Email == email && u.Password == password);

            if (admin == null)
            {
                TempData["LoginFailed"] = true;
                return Redirect("/Registration/SignIn");
            }

            HttpContext.Session.SetInt32("adminId", admin.Id);
            HttpContext.Session.SetString("fullName", admin.FullName);

            return RedirectToAction("Welcome", "Admin", null);
        }

        public IActionResult Logout()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return View("Views/Users/PageNotFound.cshtml");
            }

            HttpContext.Session.Remove("adminId");
            return RedirectToAction("Index", "Home", null);
        }
    }
}

final-project/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TheSmartyColman</title>

    <!--Load CSS-->
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="~/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand" href="#">The Smarty Colman - Admin Panel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav navbar-center">
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Orders">Orders</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Costumers">Costumers</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Categories">Categories</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Branches">Branches</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Statistics">Statistics</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="EditProducts">Products</a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Admins">Admins</a>
                </div>
                <div class="float-right d-flex">
                    <a class="nav-link" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                </div>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div>
        <div class="container view-container">

            @RenderBody()

        </div>
        <hr />
        <footer>
            <div class="row">
                <p class="col-md-6">&copy; 2021 - final project by Aviya Shirian, Ofir Inbar, Shay Cohen</p>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/bingMap.js"></script>
        <script src="~/js/facebookService.js"></script>
        <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&branch=experimental&setMkt=he-IL&setLang=he&key=ApxKkcD7MByeyxSCRDPy27su9HDczhlYFmI96NQDgpTtdHXdNkLr2922DcqjyKad' async defer></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/bingMap.js"></script>
        <script src="~/js/facebookService.js"></script>
        <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&branch=experimental&setMkt=he-IL&setLang=he&key=ApxKkcD7MByeyxSCRDPy27su9HDczhlYFmI96NQDgpTtdHXdNkLr2922DcqjyKad' async defer></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

final-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/images/book.svg">
    <title>The Smarty Colman</title>

    <!--Load CSS-->
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="~/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/animate.css-master/animate.min.css">
        <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/bingMap.js"></script>
        <script src="~/js/facebookService.js"></script>
        <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&branch=experimental&setMkt=he-IL&setLang=he&key=ApxKkcD7MByeyxSCRDPy27su9HDczhlYFmI96NQDgpTtdHXdNkLr2922DcqjyKad' async defer></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/js/script.js"></script>
        <script src="~/js/bingMap.js"></script>
        <script src="~/js/facebookService.js"></script>
        <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&branch=experimental&setMkt=he-IL&setLang=he&key=ApxKkcD7MByeyxSCRDPy27su9HDczhlYFmI96NQDgpTtdHXdNkLr2922DcqjyKad' async defer></script>
    </environment>

</head>
<body>
    <nav class="navbar navbar-light">
        <div class="d-flex justify-content-between">
            <div class="navbar">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Shop">Shop</a>
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="">
                <h2 class="navbar-title">The Smarty Colman</h2>
            </a>
        </div>
        <div class="d-flex justify-content-between">
            <div class="navbar">
                <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Cart">Cart</a> 
                <a class="nav-link" asp-area="" asp-controller="Registration" asp-action="SignIn">Admin</a> 
            </div>
            </div>
</nav>
    <div>
        @RenderBody()
        <footer>
            <div class="row layout-footer">
                <p class="">&copy; 2021 - final project by Aviya Shirian, Ofir Inbar, Shay Cohen</p>

                <div class="fb-share-button" style="position: relative; top: -10px;"
                     data-href="https://breastfeedinglaw.com/wp-content/uploads/2020/06/book.jpeg"
                     data-size="large" data-mobile-iframe="true">
                    <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse"
                       class="fb-xfbml-parse-ignore">
                    </a>
                </div>
            </div>
        </footer>
    </div>



    @RenderSection("Scripts", required: false)

    <script src="~/lib/WOW-master/dist/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>
</body>

</html>